version: "3.8"

services:
  animal-sudoku-app-service:
    container_name: animal-sudoku-app-container

    image: takanarishimbo/animal-sudoku-app:v2.2.1

    ports:
      - "${SERVER_PORT}:8501"

    command: streamlit run server.py

    restart: always
